/**
 * This file has been autogenerated as it didn't exist or was made for an older
 * incompatible version.
 *
 * This file can be used for manual configuration. It will not be modified
 * if the flowDefaults constant exists.
 */
const merge = require('webpack-merge');
const flowDefaults = require('./webpack.generated.js');

/**
 * To change the webpack config, add a new configuration object in
 * the merge arguments below:
 */

// https://github.com/vaadin/flow/issues/6953
flowDefaults.module.rules = flowDefaults.module.rules.filter(
  (rule) => !rule.test.test('.css')
);
const merged = merge(flowDefaults, {
  module: {
    rules: [
      {
        test: /\.css$/i,
        use: ['lit-css-loader'],
      },
    ],
  },
});
console.log(merged.module.rules);
module.exports = merged;
